# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communication.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ommunication.proto\x12\rcommunication\",\n\x07Request\x12\x10\n\x08sequence\x18\x01 \x01(\x05\x12\x0f\n\x07payload\x18\x02 \x01(\t\"1\n\x08Response\x12\x10\n\x08sequence\x18\x01 \x01(\x05\x12\x13\n\x0bisprocessed\x18\x02 \x01(\x08\x42\nZ\x08./engineb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'communication_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010./engine'
  _REQUEST._serialized_start=38
  _REQUEST._serialized_end=82
  _RESPONSE._serialized_start=84
  _RESPONSE._serialized_end=133
# @@protoc_insertion_point(module_scope)
